name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/caption-me-api || exit 1
            git pull || exit 1
            mkdir -p logs
            touch .env
            echo "${{ secrets.PROD }}" > .env
            pnpm install --frozen-lockfile || exit 1
            pnpm build || exit 1
            pm2 reload ecosystem.config.js --update-env || exit 1
